In [1]:
print("My sentiment analysis project started")

My sentiment analysis project started


In [2]:
from textblob import TextBlob
import pandas as pd
import matplotlib.pyplot as plt

print("Libraries imported successfully")

Libraries imported successfully


In [ ]:
from textblob import TextBlob
import pandas as pd
import matplotlib.pyplot as plt

print("Libraries imported successfully")

In [ ]:
def analyze_sentiment(text):
    """Analyze sentiment of a single text"""
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity
    
    # Convert polarity to simple labels
    if polarity > 0.1:
        return "Positive", polarity
    elif polarity < -0.1:
        return "Negative", polarity
    else:
        return "Neutral", polarity

# Test the function
test_text = "I love this product! It's amazing!"
sentiment, score = analyze_sentiment(test_text)
print(f"Text: {test_text}")
print(f"Sentiment: {sentiment}")
print(f"Score: {score}")

In [ ]:

sample_posts = [
    "Just got the new iPhone! Love it so much! ",
    "This product is terrible. Waste of money ",
    "The weather is okay today",
    "Best customer service ever! Thank you so much!",
    "Worst experience ever. Never buying again.",
    "Netflix new series is incredible! Binge watching all night ",
    "Traffic is so bad today ",
    "Happy Friday everyone! "
]

results = []
for post in sample_posts:
    sentiment, score = analyze_sentiment(post)
    results.append({
        'text': post,
        'sentiment': sentiment, 
        'score': score
    })
    print(f"{sentiment}: {post}")

In [ ]:
df=pd.DataFrame(results)
print("Sentiment Analysis Results:")
print(df)

sentiment_counts = df['sentiment'].value_counts()
print(f"\nSentiment Distribution:")
print(sentiment_counts)

total_posts = len(df)
for sentiment in sentiment_counts.index:
    count = sentiment_counts[sentiment]
    percentage = (count/total_posts) * 100
    print(f"{sentiment}: {count} posts ({percentage:.1f}%)")

In [ ]:
plt.figure(figsize=(10, 5))

# Pie chart
plt.subplot(1, 2, 1)
sentiment_counts.plot(kind='pie', autopct='%1.1f%%')
plt.title('Sentiment Distribution')
plt.ylabel('')

# Bar chart
plt.subplot(1, 2, 2)
sentiment_counts.plot(kind='bar', color=['green', 'red', 'gray'])
plt.title('Sentiment Count')
plt.xlabel('Sentiment')
plt.ylabel('Number of Posts')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

In [ ]:
def analyze_multiple_posts(posts, topic="General"):
    """Analyze sentiment for multiple posts"""
    results = []
    
    for post in posts:
        sentiment, score = analyze_sentiment(post)
        results.append({
            'text': post,
            'sentiment': sentiment,
            'score': score
        })
    
    # Create summary
    df = pd.DataFrame(results)
    print(df)
    sentiment_counts = df['sentiment'].value_counts()
    
    print(f"=== SENTIMENT ANALYSIS REPORT: {topic} ===")
    print(f"Total posts analyzed: {len(posts)}")
    print(f"Positive: {sentiment_counts.get('Positive', 0)} ({sentiment_counts.get('Positive', 0)/len(posts)*100:.1f}%)")
    print(f"Negative: {sentiment_counts.get('Negative', 0)} ({sentiment_counts.get('Negative', 0)/len(posts)*100:.1f}%)")
    print(f"Neutral: {sentiment_counts.get('Neutral', 0)} ({sentiment_counts.get('Neutral', 0)/len(posts)*100:.1f}%)")
    
    return df

# Test it
report = analyze_multiple_posts(sample_posts, "Sample  Social Media Posts")

In [ ]:
import shutil


In [ ]:
import os

In [ ]:
os.makedirs(os.path.expanduser("~/.kaggle"), exist_ok=True)

In [ ]:
os.chmod(os.path.expanduser("~/.kaggle/kaggle.json"), 0o600)

In [ ]:
os.chmod(os.path.expanduser("~/.kaggle/kaggle.json"), 0o600)


In [ ]:
shutil.move("kaggle.json", os.path.expanduser("~/.kaggle/kaggle.json"))


In [ ]:
os.chmod(os.path.expanduser("~/.kaggle/kaggle.json"), 0o600)


In [ ]:
!kaggle datasets download -d kazanova/sentiment140


In [ ]:
import zipfile

with zipfile.ZipFile("sentiment140.zip", 'r') as zip_ref:
    zip_ref.extractall("sentiment140-data")


In [1]:
import pandas as pd

# The extracted file is named 'training.1600000.processed.noemoticon.csv'
df = pd.read_csv("sentiment140-data/training.1600000.processed.noemoticon.csv", 
                 encoding='latin-1', header=None)

# Optional: Give column names
df.columns = ['target', 'ids', 'date', 'flag', 'user', 'text']

# Show first few rows
df.head()


target         ids                          date      flag  \
0       0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1       0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2       0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3       0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4       0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   

              user                                               text  
0  _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1    scotthamilton  is upset that he can't update his Facebook by ...  
2         mattycus  @Kenichan I dived many times for the ball. Man...  
3          ElleCTF    my whole body feels itchy and like its on fire   
4           Karoli  @nationwideclass no, it's not behaving at all....

 So far I have used Kaggle API to download the sentiment140 dataset that is the tweets from Twitter API with more than 1.6 million tweets. I loaded the dataset and now its ready for preprocessing.

In [2]:
import re
import emoji 
import spacy
import nltk
from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords

In [3]:
pip install emoji


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import re
import emoji 
import spacy
import nltk
from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords

In [3]:
pip install spacy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [6]:
import re
import emoji 
import spacy
import nltk
from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords

Imported different libraries for text preprocessing . re lib for removing patterns like url, hashtags. emoji lib for converting emojis to text to help the model learn from them. spaCy lib for lemmatization that is converting words to their normal form. eg:- running to run. nltk.corpus.stopwords for removing common but unhelpful words like "the", "is", "on". nltk.tokenize.TweetTokenizer used for tokenizing words that is  to split text into words, specifically optimized for social media content. 

In [7]:
nltk.download('stopwords')
nlp = spacy.load('en_core_web_sm')

stop_words = set(stopwords.words('english'))
tokenizer = TweetTokenizer()

[nltk_data] Downloading package stopwords to /home/aniduh/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [8]:
import re
import emoji 
import spacy
import nltk
from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords

In [9]:
nltk.download('stopwords')
nlp = spacy.load('en_core_web_sm')

stop_words = set(stopwords.words('english'))
tokenizer = TweetTokenizer()

[nltk_data] Downloading package stopwords to /home/aniduh/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [10]:
def clean_tweet(text):
    # Convert emojis to text
    text = emoji.demojize(text)
    
    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", '', text, flags=re.MULTILINE)
    
    # Remove mentions and hashtags
    text = re.sub(r'\@\w+|\#', '', text)
    
    # Remove non-alphanumeric characters (except spaces)
    text = re.sub(r"[^\w\s]", "", text)
    
    # Lowercase
    text = text.lower()
    
    # Tokenize using TweetTokenizer
    tokens = tokenizer.tokenize(text)
    
    # Remove stopwords
    tokens = [word for word in tokens if word not in stop_words and word.isalpha()]
    
    # Lemmatize using spaCy
    doc = nlp(" ".join(tokens))
    lemmatized = [token.lemma_ for token in doc]

    return " ".join(lemmatized)

In [ ]:
sample_tweet = "Wow!!! I love #AI 😍😍. Check this out: https://t.co/xyz @elonmusk"
cleaned_output = clean_tweet(sample_tweet)
print("Original Tweet:")
print(sample_tweet)
print("\nCleaned Output:")
print(cleaned_output)

In [ ]:
sample_tweet = "Wow!!! I loved #AI 😍😍. Check this out: https://t.co/xyz @elonmusk"
cleaned_output = clean_tweet(sample_tweet)
print("Original Tweet:")
print(sample_tweet)
print("\nCleaned Output:")
print(cleaned_output)

In [ ]:
def clean_tweet(tweet):
    # 1. Convert emojis to text (😍 → :smiling_face_with_heart_eyes:)
    tweet = emoji.demojize(tweet)

    # 2. Remove URLs
    tweet = re.sub(r'http\S+|www.\S+', '', tweet)

    # 3. Remove mentions and hashtags (optional: keep usernames/words if you want)
    tweet = re.sub(r'@\w+', '', tweet)
    tweet = re.sub(r'#', '', tweet)

    # 4. Remove punctuation and numbers
    tweet = re.sub(r'[^a-zA-Z_: ]', '', tweet)

    # 5. Lowercase
    tweet = tweet.lower()

    # 6. Tokenize
    tokens = tokenizer.tokenize(tweet)

    # 7. Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # 8. Lemmatization
    doc = nlp(" ".join(tokens))
    lemmas = [token.lemma_ for token in doc if token.lemma_ != "-PRON-"]

    return lemmas

In [ ]:
sample_tweet = "Wow!!! I loved #AI 😍😍. Check this out: https://t.co/xyz @elonmusk"
cleaned_output = clean_tweet(sample_tweet)
print("Original Tweet:")
print(sample_tweet)
print("\nCleaned Output:")
print(cleaned_output)

In [ ]:
def clean_tweet(tweet):
    # 1. Convert emoji to text (😍 → :smiling_face_with_heart_eyes:)
    tweet = emoji.demojize(tweet)

    # 2. Remove URLs
    tweet = re.sub(r'http\S+|www.\S+', '', tweet)

    # 3. Remove mentions and hashtags
    tweet = re.sub(r'@\w+', '', tweet)
    tweet = re.sub(r'#', '', tweet)

    # 4. Remove punctuation except colons (needed temporarily)
    tweet = re.sub(r'[^a-zA-Z0-9_: ]', '', tweet)

    # 5. Lowercase
    tweet = tweet.lower()

    # 6. Replace emoji format ":emoji_name:" → "emoji_name"
    tweet = re.sub(r':([a-zA-Z_]+):', r'\1', tweet)

    # 7. Tokenize
    tokens = tokenizer.tokenize(tweet)

    # 8. Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # 9. Lemmatization
    doc = nlp(" ".join(tokens))
    lemmas = [token.lemma_ for token in doc if token.lemma_ != "-PRON-"]

    return lemmas

In [ ]:
tweet = "Wow!!! I love #AI 😍😍. Check this out: https://t.co/xyz @elonmusk"
print(clean_tweet(tweet))

In [ ]:


def clean_tweet(tweet):
    # 1. Convert emojis to text with space in between
    tweet = emoji.demojize(tweet, delimiters=(" ", " "))

    # 2. Remove URLs
    tweet = re.sub(r'http\S+|www.\S+', '', tweet)

    # 3. Remove mentions and hashtags
    tweet = re.sub(r'@\w+', '', tweet)
    tweet = re.sub(r'#', '', tweet)

    # 4. Remove unwanted punctuation (keep colon temporarily)
    tweet = re.sub(r'[^a-zA-Z0-9_: ]', '', tweet)

    # 5. Lowercase
    tweet = tweet.lower()

    # 6. Replace emoji format ":emoji_name:" → "emoji_name"
    tweet = re.sub(r':([a-zA-Z_]+):', r'\1', tweet)

    # 7. Tokenize
    tokens = tokenizer.tokenize(tweet)

    # 8. Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # 9. Lemmatize
    doc = nlp(" ".join(tokens))
    lemmas = [token.lemma_ for token in doc if token.lemma_ != "-PRON-"]

    return lemmas

In [ ]:
tweet = "Wow!!! I loved #AI 😍😍. Check this out: https://t.co/xyz @elonmusk"
print(clean_tweet(tweet))


In [ ]:
def clean_tweet(tweet):
    # 1. Convert emoji to text
    tweet = emoji.demojize(tweet)

    # 👉 Add a space between each emoji text block (e.g., ":emoji1::emoji2:" → ":emoji1: :emoji2:")
    tweet = re.sub(r'(:[a-z_]+:)(?=:[a-z_]+:)', r'\1 ', tweet)

    # 2. Remove URLs
    tweet = re.sub(r'http\S+|www.\S+', '', tweet)

    # 3. Remove mentions and hashtags
    tweet = re.sub(r'@\w+', '', tweet)
    tweet = re.sub(r'#', '', tweet)

    # 4. Remove punctuation except colons
    tweet = re.sub(r'[^a-zA-Z0-9_: ]', '', tweet)

    # 5. Lowercase
    tweet = tweet.lower()

    # 6. Replace emoji format ":emoji_name:" → "emoji_name"
    tweet = re.sub(r':([a-zA-Z_]+):', r'\1', tweet)

    # 7. Tokenize
    tokens = tokenizer.tokenize(tweet)

    # 8. Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # 9. Lemmatization
    doc = nlp(" ".join(tokens))
    lemmas = [token.lemma_ for token in doc if token.lemma_ != "-PRON-"]

    return lemmas

In [ ]:
tweet = "Wow!!! I love #AI 😍😍. Check this out: https://t.co/xyz @elonmusk"
print(clean_tweet(tweet))

In [2]:
import re
import emoji
import nltk
import spacy
from nltk.corpus import stopwords
from nltk.tokenize import TweetTokenizer

# Setup
nltk.download('stopwords')
nlp = spacy.load('en_core_web_sm')
stop_words = set(stopwords.words('english'))
tokenizer = TweetTokenizer()

def clean_tweet(tweet):
    # 1. Convert emojis to text with spaces between
    tweet = emoji.demojize(tweet, delimiters=(" ", " "))  # 😍😍 → ' smiling_face_with_heart_eyes  smiling_face_with_heart_eyes '

    # 2. Remove URLs
    tweet = re.sub(r"http\S+|www.\S+", "", tweet)

    # 3. Remove mentions and hashtags
    tweet = re.sub(r"@\w+", "", tweet)
    tweet = tweet.replace("#", "")

    # 4. Remove special characters (keep underscores for emoji text)
    tweet = re.sub(r"[^a-zA-Z0-9_ ]+", "", tweet)

    # 5. Lowercase
    tweet = tweet.lower()

    # 6. Tokenize
    tokens = tokenizer.tokenize(tweet)

    # 7. Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # 8. Lemmatize
    doc = nlp(" ".join(tokens))
    lemmas = [token.lemma_ for token in doc if token.lemma_ != "-PRON-"]

    return lemmas


[nltk_data] Downloading package stopwords to /home/aniduh/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [12]:
tweet = "Wow!!! I love #AI 😍😍. Check this out: https://t.co/xyz @elonmusk"
print(clean_tweet(tweet))

['wow', 'love', 'ai', 'smiling_face_with_hearteyes', 'smiling_face_with_hearteye', 'check']


### 🔄 Emoji Conversion & Tweet Cleaning

We convert emojis into human-readable text using `emoji.demojize()` and clean the tweets by removing URLs, mentions, hashtags, and special characters. This ensures uniform text input for downstream processing.

### ⚙️ Final Preprocessing Function

The full `clean_tweet()` function combines all steps — emoji conversion, cleaning, tokenization, stopword removal, and lemmatization — into a reusable method for preprocessing raw tweets.


In [5]:
pip install scikit-learn


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
df_sample = df.sample(5000, random_state=42)

In [4]:
print("Hello")

Hello


In [5]:
df_sample = df.sample(5000, random_state=42)

In [6]:
cleaned_tweets = df_sample['text'].apply(clean_tweet)

In [18]:
print("Preprocessing sample done.")


Preprocessing sample done.


In [19]:
texts = [' '.join(tokens) for tokens in cleaned_tweets]


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the vectorizer
vectorizer = TfidfVectorizer(max_features=5000)  # Limit vocabulary size

# Fit and transform
X = vectorizer.fit_transform(texts)

# Check results
print("TF-IDF matrix shape:", X.shape)
print("First 10 feature names:", vectorizer.get_feature_names_out()[:10])


TF-IDF matrix shape: (5000, 5000)
First 10 feature names: ['08' '09' '10' '100' '1000' '100000' '10000000' '1000th' '1002am' '10100']


Done with the TF-IDF VECTORIZATION, that is the input data "X" is ready for model to learn


In [21]:
y = df_sample['target'].replace({0: 0, 4: 1})

In [22]:
print("Label counts:")
print(y.value_counts())


Label counts:
target
1    2504
0    2496
Name: count, dtype: int64


Done with preparing the target labels or known outputs(Y) which is also known as Sentiment labels. 0 means negative tweets and 4 means positive tweets here so for machine understanding we are converting 0 to 0 and 4 to 1 for binary purpose.

In [23]:
from sklearn.model_selection import train_test_split

# Split into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


So we are splitting the data into 80 percent training set and 20 percent testing set. We give 80 percent training set to train the model and 20 percent to test the performance of model with the new tweets with the previous training we did to it.

In [24]:
from sklearn.linear_model import LogisticRegression

# Initialize the model
model = LogisticRegression(max_iter=1000)

# Train on the training data
model.fit(X_train, y_train)

print("Model training completed.")


Model training completed.


Completed training of sentiment classification model using Logistic Regression which is effective in binary classification and fast.

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Predict on the test set
y_pred = model.predict(X_test)

# Print evaluation metrics
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.702

Confusion Matrix:
 [[338 158]
 [140 364]]

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.68      0.69       496
           1       0.70      0.72      0.71       504

    accuracy                           0.70      1000
   macro avg       0.70      0.70      0.70      1000
weighted avg       0.70      0.70      0.70      1000



In [26]:
print(df_sample['target'].value_counts())


target
4    2504
0    2496
Name: count, dtype: int64


In [27]:
df_sample['target'] = df_sample['target'].replace(4, 1)


In [28]:
print(df_sample['target'].value_counts())


target
1    2504
0    2496
Name: count, dtype: int64


So I have completed the evaluation of the model by testing it on 1000 tweets which is the 20 percent of 5000 tweets. 338 out of 496 negative tweets were correctly classified. 364 out of 504 positive tweets were correctly classified. No major bias toward any one class. 

In [29]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

svm_model = SVC()
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))
print("Classification Report:\n", classification_report(y_test, y_pred_svm))


SVM Accuracy: 0.708
Confusion Matrix:
 [[337 159]
 [133 371]]
Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.68      0.70       496
           1       0.70      0.74      0.72       504

    accuracy                           0.71      1000
   macro avg       0.71      0.71      0.71      1000
weighted avg       0.71      0.71      0.71      1000



Used Support Vector Machine model for a better classification than logistic regression.

In [30]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))


Random Forest Accuracy: 0.684
Confusion Matrix:
 [[326 170]
 [146 358]]
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.66      0.67       496
           1       0.68      0.71      0.69       504

    accuracy                           0.68      1000
   macro avg       0.68      0.68      0.68      1000
weighted avg       0.68      0.68      0.68      1000



Used Random Forest model 

In [28]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)

print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))
print("Classification Report:\n", classification_report(y_test, y_pred_nb))


Naive Bayes Accuracy: 0.712
Confusion Matrix:
 [[371 125]
 [163 341]]
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.75      0.72       496
           1       0.73      0.68      0.70       504

    accuracy                           0.71      1000
   macro avg       0.71      0.71      0.71      1000
weighted avg       0.71      0.71      0.71      1000



Used Naive Bayes model which gave the higest accuracy of classification compared to other models.

In [10]:
pip install joblib

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [11]:
import joblib

# Save trained Naive Bayes model
joblib.dump(nb_model, "sentiment_model_nb.pkl")

# Save the fitted TF-IDF vectorizer
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print("Model and vectorizer saved successfully!")


NameError: name 'nb_model' is not defined

In [9]:
import joblib

# Load the model and vectorizer
modelz = joblib.load("sentiment_model_nb.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")


In [ ]:
def preprocess_for_prediction(tweet):
    tokens = clean_tweet(tweet)               # Reuse your existing clean_tweet function
    text = " ".join(tokens)                   # Convert tokens back to a string
    return text


In [ ]:
# Example tweet
new_tweet = "I don't Hate jews and Indians and naveen"

# Preprocess
cleaned_text = preprocess_for_prediction(new_tweet)

# Vectorize
X_new = vectorizer.transform([cleaned_text])

# Predict
prediction = modelz.predict(X_new)

# Decode sentiment
sentiment = "Positive" if prediction[0] == 1 else "Negative"
print("Predicted Sentiment:", sentiment)


Loaded our trained model and tested with new tweet for classification

In [35]:
# Example tweet
new_tweet = "I Love football"

# Preprocess
cleaned_text = preprocess_for_prediction(new_tweet)

# Vectorize
X_new = vectorizer.transform([cleaned_text])

# Predict
prediction = modelz.predict(X_new)

# Decode sentiment
sentiment = "Positive" if prediction[0] == 1 else "Negative"
print("Predicted Sentiment:", sentiment)


Predicted Sentiment: Positive


In [12]:
pip install transformers torch 

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [11]:
import torch
from transformers import DistilBertTokenizer, DistilBertModel
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import pandas as pd
import numpy as np


In [34]:
df_sample = df_sample[df_sample['target'].isin([0, 4])]
df_sample['target'] = df_sample['target'].apply(lambda x: 1 if x == 4 else 0)


In [35]:
def get_bert_embedding(text):
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=128)
    with torch.no_grad():
        outputs = model(**inputs)
    # Use the [CLS] token embedding as sentence representation
    return outputs.last_hidden_state[:, 0, :].squeeze().numpy()


In [36]:
df['target'] = df['target'].replace(4, 1)  # If 4 means positive, convert it to 1

# Check class balance
print(df['target'].value_counts())


target
0    800000
1    800000
Name: count, dtype: int64


In [37]:
n = min(df['target'].value_counts())
df_balanced = pd.concat([
    df[df['target'] == 0].sample(n, random_state=42),
    df[df['target'] == 1].sample(n, random_state=42)
])

df_balanced = df_balanced.sample(frac=1).reset_index(drop=True)  # Shuffle

In [38]:
from transformers import DistilBertTokenizer, DistilBertModel
import torch
import numpy as np

# Load tokenizer and model
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertModel.from_pretrained('distilbert-base-uncased')
model.eval()  # Set model to evaluation mode


DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0-5): 6 x TransformerBlock(
        (attention): DistilBertSdpaAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): L

In [39]:
texts = df_sample['text'].tolist()[:500]  # Limit to 500 for now
labels = df_sample['target'].tolist()[:500]


In [40]:
import numpy as np
from tqdm import tqdm  # Optional: for progress bar

embeddings = []

for text in tqdm(texts, desc="Embedding tweets"):
    try:
        inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=128)
        with torch.no_grad():
            outputs = model(**inputs)
            cls_embedding = outputs.last_hidden_state[:, 0, :]  # Use [CLS]-like token
            embeddings.append(cls_embedding.squeeze().numpy())
    except Exception as e:
        print("Error in embedding:", text, "\n", e)
        embeddings.append(np.zeros(768))  # Handle problematic texts with zeros

embeddings = np.array(embeddings)


Embedding tweets: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:14<00:00, 34.01it/s]


In [35]:
print("Embeddings shape:", embeddings.shape)  # Should be (500, 768)


Embeddings shape: (500, 768)


In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(embeddings, labels, test_size=0.2, random_state=42)

clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))


ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: np.int64(0)

In [ ]:
from collections import Counter
print(Counter(labels))


In [42]:
# Replace 4 with 1 for positive sentiment
df_sample['target'] = df_sample['target'].replace(4, 1)

# Sample balanced dataset
positive_samples = df_sample[df_sample['target'] == 1].sample(250, random_state=42)
negative_samples = df_sample[df_sample['target'] == 0].sample(250, random_state=42)

# Combine
balanced_df = pd.concat([positive_samples, negative_samples])

# Get texts and labels
texts = balanced_df['text'].tolist()
labels = balanced_df['target'].tolist()


ValueError: a must be greater than 0 unless no samples are taken

In [ ]:
print(df_sample['target'].value_counts())


In [43]:
# Start fresh from full dataset
df = pd.read_csv('sentiment140-data/training.1600000.processed.noemoticon.csv', encoding='latin-1', header=None)
df.columns = ['target', 'id', 'date', 'flag', 'user', 'text']


In [44]:
df['target'] = df['target'].replace(4, 1)  # Convert 4s to 1s (positive)


In [45]:
positive_df = df[df['target'] == 1].sample(2500, random_state=42)
negative_df = df[df['target'] == 0].sample(2500, random_state=42)

df_sample = pd.concat([positive_df, negative_df]).sample(frac=1, random_state=42)  # Shuffle


In [46]:
# Load tokenizer and model
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertModel.from_pretrained('distilbert-base-uncased')
model.eval()  # Set model to evaluation mode


DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0-5): 6 x TransformerBlock(
        (attention): DistilBertSdpaAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): L

In [47]:
def get_distilbert_embedding(text):
    with torch.no_grad():
        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128)
        outputs = model(**inputs)
        cls_embedding = outputs.last_hidden_state[:, 0, :].squeeze().numpy()
    return cls_embedding


In [48]:
texts = df_sample['text'].tolist()
labels = df_sample['target'].tolist()

embeddings = np.array([get_distilbert_embedding(text) for text in tqdm(texts)])


100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [02:14<00:00, 37.12it/s]


In [49]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

X_train, X_test, y_train, y_test = train_test_split(
    embeddings, labels, test_size=0.2, random_state=42
)


In [65]:
nb = GaussianNB()
nb.fit(X_train, y_train)


GaussianNB()

In [66]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = nb.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.674

Confusion Matrix:
 [[340 184]
 [142 334]]

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.65      0.68       524
           1       0.64      0.70      0.67       476

    accuracy                           0.67      1000
   macro avg       0.68      0.68      0.67      1000
weighted avg       0.68      0.67      0.67      1000



In [67]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# texts and labels already defined
# embeddings already generated using DistilBERT
X_train, X_test, y_train, y_test = train_test_split(
    embeddings, labels, test_size=0.2, random_state=42
)


In [68]:
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)


LogisticRegression(max_iter=1000)

In [69]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = clf.predict(X_test)

print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n📊 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\n📋 Classification Report:\n", classification_report(y_test, y_pred))


✅ Accuracy: 0.757

📊 Confusion Matrix:
 [[372 152]
 [ 91 385]]

📋 Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.71      0.75       524
           1       0.72      0.81      0.76       476

    accuracy                           0.76      1000
   macro avg       0.76      0.76      0.76      1000
weighted avg       0.76      0.76      0.76      1000



In [70]:
import pickle

with open('distilbert_logistic_model.pkl', 'wb') as f:
    pickle.dump(clf, f)


In [71]:
with open('distilbert_logistic_model.pkl', 'rb') as f:
    model = pickle.load(f)


SUMMARY TILL NOW

Step 1: Dataset Used

    Sentiment140 from Kaggle

    File: training.1600000.processed.noemoticon.csv

    Contains 1.6 million tweets labeled with:

        0: Negative sentiment

        4: Positive sentiment (converted to 1)

Step 2: Preprocessing Pipeline

    Emoji conversion → e.g., 😍 → smiling_face_with_heart_eyes

    URL removal

    User mention & hashtag removal

    Special character cleaning

    Lowercasing

    Tokenization using TweetTokenizer

    Stopword removal (NLTK)

    Lemmatization using spaCy
    
Step 3: Baseline Model — TF-IDF + Naive Bayes

    Model: Multinomial Naive Bayes

    Accuracy: ~70%

    Simple, fast, and interpretable

Step 4: Improved Model — DistilBERT + Logistic Regression

    Tokenized using DistilBertTokenizer

    Passed through DistilBertModel

    Used CLS token embedding (768-dimensional)

    Model trained using Logistic Regression with improved accuracy of 75%

Step 5: Model Saving

    Used pickle to save:

        sentiment_model.pkl → Logistic Regression model

        tfidf_vectorizer.pkl → For TF-IDF model

In [46]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from torch.utils.data import TensorDataset, DataLoader

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    embeddings, labels, test_size=0.2, random_state=42)

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)

# DataLoader
train_loader = DataLoader(TensorDataset(X_train_tensor, y_train_tensor), batch_size=32, shuffle=True)

# Define the MLP
class MLP(nn.Module):
    def __init__(self, input_dim):
        super(MLP, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.net(x)

# Initialize model
mlp_model = MLP(X_train.shape[1])
criterion = nn.BCELoss()
optimizer = optim.Adam(mlp_model.parameters(), lr=1e-4)

# Training loop
for epoch in range(10):
    mlp_model.train()
    epoch_loss = 0
    for xb, yb in train_loader:
        optimizer.zero_grad()
        pred = mlp_model(xb)
        loss = criterion(pred, yb)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
    print(f"Epoch {epoch+1}/10 - Loss: {epoch_loss:.4f}")


Epoch 1/10 - Loss: 85.5565
Epoch 2/10 - Loss: 80.1483
Epoch 3/10 - Loss: 74.0745
Epoch 4/10 - Loss: 70.7301
Epoch 5/10 - Loss: 68.2755
Epoch 6/10 - Loss: 66.8385
Epoch 7/10 - Loss: 65.7560
Epoch 8/10 - Loss: 64.9816
Epoch 9/10 - Loss: 64.0221
Epoch 10/10 - Loss: 63.8133


In [47]:
mlp_model.eval()
with torch.no_grad():
    preds = mlp_model(X_test_tensor)
    y_pred = (preds > 0.5).int().squeeze()
    y_true = y_test_tensor.int().squeeze()
    
print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred))


Accuracy: 0.767
              precision    recall  f1-score   support

           0       0.82      0.72      0.76       524
           1       0.73      0.82      0.77       476

    accuracy                           0.77      1000
   macro avg       0.77      0.77      0.77      1000
weighted avg       0.77      0.77      0.77      1000



In [1]:
# Re-import after code execution environment reset
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import classification_report, accuracy_score
from transformers import DistilBertTokenizer, DistilBertModel
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from tqdm import tqdm

# Load data
df = pd.read_csv("sentiment140-data/training.1600000.processed.noemoticon.csv", encoding='latin-1', header=None)
df.columns = ['target', 'ids', 'date', 'flag', 'user', 'text']

# Sample balanced data (1000 pos, 1000 neg)
df_sample = pd.concat([
    df[df['target'] == 0].sample(1000, random_state=42),
    df[df['target'] == 4].sample(1000, random_state=42)
]).sample(frac=1, random_state=42).reset_index(drop=True)

df_sample['target'] = df_sample['target'].map({0: 0, 4: 1})

# Load tokenizer and model
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
bert_model = DistilBertModel.from_pretrained("distilbert-base-uncased")

def get_embedding(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=64)
    with torch.no_grad():
        outputs = bert_model(**inputs)
    return outputs.last_hidden_state[:, 0, :].squeeze().numpy()

# Generate embeddings
texts = df_sample['text'].tolist()
labels = df_sample['target'].tolist()
embeddings = np.array([get_embedding(text) for text in tqdm(texts)])

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(embeddings, labels, test_size=0.2, random_state=42)

X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)

# Define MLP
class MLP(nn.Module):
    def __init__(self, input_dim):
        super(MLP, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

mlp_model = MLP(input_dim=768)
criterion = nn.BCELoss()
optimizer = optim.Adam(mlp_model.parameters(), lr=1e-4)

# Train
epochs = 20
for epoch in range(epochs):
    mlp_model.train()
    optimizer.zero_grad()
    outputs = mlp_model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)
    loss.backward()
    optimizer.step()
    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

# Evaluate
mlp_model.eval()
with torch.no_grad():
    preds = mlp_model(X_test_tensor)
    y_pred = (preds > 0.5).int().squeeze()
    y_true = y_test_tensor.int().squeeze()

accuracy = accuracy_score(y_true, y_pred)
report = classification_report(y_true, y_pred)

accuracy, report


100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [01:02<00:00, 32.23it/s]


Epoch 1/20, Loss: 0.6962
Epoch 2/20, Loss: 0.6945
Epoch 3/20, Loss: 0.6929
Epoch 4/20, Loss: 0.6924
Epoch 5/20, Loss: 0.6919
Epoch 6/20, Loss: 0.6881
Epoch 7/20, Loss: 0.6887
Epoch 8/20, Loss: 0.6852
Epoch 9/20, Loss: 0.6850
Epoch 10/20, Loss: 0.6848
Epoch 11/20, Loss: 0.6834
Epoch 12/20, Loss: 0.6833
Epoch 13/20, Loss: 0.6827
Epoch 14/20, Loss: 0.6810
Epoch 15/20, Loss: 0.6796
Epoch 16/20, Loss: 0.6778
Epoch 17/20, Loss: 0.6761
Epoch 18/20, Loss: 0.6765
Epoch 19/20, Loss: 0.6740
Epoch 20/20, Loss: 0.6733


(0.6375,
 '              precision    recall  f1-score   support\n\n           0       0.65      0.58      0.61       197\n           1       0.63      0.69      0.66       203\n\n    accuracy                           0.64       400\n   macro avg       0.64      0.64      0.64       400\nweighted avg       0.64      0.64      0.64       400\n')

In [51]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from transformers import DistilBertTokenizer, DistilBertModel
import pandas as pd
import numpy as np
from tqdm import tqdm


In [52]:
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
bert_model = DistilBertModel.from_pretrained("distilbert-base-uncased")

def get_embedding(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=64)
    with torch.no_grad():
        outputs = bert_model(**inputs)
    return outputs.last_hidden_state[:, 0, :].squeeze().numpy()

texts = df_sample['text'].tolist()
labels = df_sample['target'].tolist()

# Takes a minute...
embeddings = np.array([get_embedding(text) for text in tqdm(texts)])


100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [00:58<00:00, 34.24it/s]


In [53]:
# Train/test split
X_train, X_test, y_train, y_test = train_test_split(embeddings, labels, test_size=0.2, random_state=42)

# Convert to tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)

# DataLoader
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)


In [54]:
class MLP(nn.Module):
    def __init__(self, input_dim):
        super(MLP, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

mlp_model = MLP(input_dim=768)
criterion = nn.BCELoss()
optimizer = optim.Adam(mlp_model.parameters(), lr=1e-4)


In [55]:
epochs = 10
for epoch in range(epochs):
    mlp_model.train()
    total_loss = 0

    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = mlp_model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    
    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss:.4f}")


Epoch 1/10, Loss: 34.2070
Epoch 2/10, Loss: 33.2216
Epoch 3/10, Loss: 32.4797
Epoch 4/10, Loss: 31.6639
Epoch 5/10, Loss: 30.9038
Epoch 6/10, Loss: 30.3930
Epoch 7/10, Loss: 29.8502
Epoch 8/10, Loss: 29.3655
Epoch 9/10, Loss: 28.9396
Epoch 10/10, Loss: 28.6163


In [56]:
mlp_model.eval()
with torch.no_grad():
    preds = mlp_model(X_test_tensor)
    y_pred = (preds > 0.5).int().squeeze()
    y_true = y_test_tensor.int().squeeze()

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred))


Accuracy: 0.695
              precision    recall  f1-score   support

           0       0.75      0.57      0.65       197
           1       0.66      0.82      0.73       203

    accuracy                           0.69       400
   macro avg       0.71      0.69      0.69       400
weighted avg       0.71      0.69      0.69       400



In [57]:
class ImprovedMLP(nn.Module):
    def __init__(self, input_dim):
        super(ImprovedMLP, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256, 64),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

# Initialize
mlp_model = ImprovedMLP(input_dim=768)
criterion = nn.BCELoss()
optimizer = optim.Adam(mlp_model.parameters(), lr=3e-5)


In [58]:
epochs = 15
for epoch in range(epochs):
    mlp_model.train()
    total_loss = 0

    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = mlp_model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    
    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss:.4f}")


Epoch 1/15, Loss: 34.6099
Epoch 2/15, Loss: 34.4790
Epoch 3/15, Loss: 34.3174
Epoch 4/15, Loss: 34.0699
Epoch 5/15, Loss: 33.7786
Epoch 6/15, Loss: 33.4576
Epoch 7/15, Loss: 33.0328
Epoch 8/15, Loss: 32.6803
Epoch 9/15, Loss: 32.2205
Epoch 10/15, Loss: 31.8335
Epoch 11/15, Loss: 31.3434
Epoch 12/15, Loss: 30.8739
Epoch 13/15, Loss: 30.4642
Epoch 14/15, Loss: 30.0502
Epoch 15/15, Loss: 29.7013


In [59]:
mlp_model.eval()
with torch.no_grad():
    preds = mlp_model(X_test_tensor)
    y_pred = (preds > 0.5).int().squeeze()
    y_true = y_test_tensor.int().squeeze()

print("Accuracy:", accuracy_score(y_true, y_pred))
print(classification_report(y_true, y_pred))


Accuracy: 0.69
              precision    recall  f1-score   support

           0       0.72      0.60      0.66       197
           1       0.67      0.77      0.72       203

    accuracy                           0.69       400
   macro avg       0.69      0.69      0.69       400
weighted avg       0.69      0.69      0.69       400



In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from transformers import DistilBertTokenizer, DistilBertModel
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from tqdm import tqdm
import pandas as pd


In [13]:
texts = df_sample['text'].tolist()
labels = df_sample['target'].tolist()

tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")


In [4]:
class TextDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors='pt'
        )
        return {
            'input_ids': encoding['input_ids'].squeeze(),
            'attention_mask': encoding['attention_mask'].squeeze(),
            'label': torch.tensor(self.labels[idx], dtype=torch.float)
        }


In [5]:
X_train, X_test, y_train, y_test = train_test_split(texts, labels, test_size=0.2, random_state=42)

train_dataset = TextDataset(X_train, y_train, tokenizer, max_len=256)
test_dataset = TextDataset(X_test, y_test, tokenizer, max_len=256)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)


In [6]:
class DistilBERTClassifier(nn.Module):
    def __init__(self):
        super(DistilBERTClassifier, self).__init__()
        self.bert = DistilBertModel.from_pretrained("distilbert-base-uncased")
        self.dropout = nn.Dropout(0.5)
        self.fc = nn.Linear(768, 1)

    def forward(self, input_ids, attention_mask):
        output = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_token = output.last_hidden_state[:, 0]
        x = self.dropout(cls_token)
        x = self.fc(x)
        return x  # No sigmoid here


In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = DistilBERTClassifier().to(device)

pos_weight = torch.tensor([1.2]).to(device)  # You can experiment: try 1.2, 1.5, 2.0
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = optim.Adam(model.parameters(), lr=2e-5, weight_decay=0.01)


from transformers import get_scheduler

epochs = 10
num_training_steps = len(train_loader) * epochs

lr_scheduler = get_scheduler(
    name="linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)
print(classification_report(true_labels, pred_labels))



NameError: name 'true_labels' is not defined

In [80]:
epochs = 9

for epoch in range(epochs):
    model.train()
    total_loss = 0
    for batch in tqdm(train_loader):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].unsqueeze(1).to(device)

        optimizer.zero_grad()
        outputs = model(input_ids, attention_mask)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss:.4f}")


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:56<00:00,  1.77s/it]


Epoch 1/9, Loss: 63.4649


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [03:03<00:00,  1.84s/it]


Epoch 2/9, Loss: 47.3620


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [03:02<00:00,  1.83s/it]


Epoch 3/9, Loss: 33.5456


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [03:05<00:00,  1.85s/it]


Epoch 4/9, Loss: 23.0324


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [03:02<00:00,  1.82s/it]


Epoch 5/9, Loss: 18.2774


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [03:04<00:00,  1.85s/it]


Epoch 6/9, Loss: 11.1319


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [03:03<00:00,  1.83s/it]


Epoch 7/9, Loss: 7.8352


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [03:02<00:00,  1.82s/it]


Epoch 8/9, Loss: 4.1966


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [03:05<00:00,  1.85s/it]

Epoch 9/9, Loss: 4.6472


In [74]:
from sklearn.metrics import classification_report

model.eval()
preds = []
true_labels = []

with torch.no_grad():
    for batch in test_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].unsqueeze(1).to(device)

        outputs = model(input_ids, attention_mask)
        probs = torch.sigmoid(outputs)  # shape: (batch_size, 1)

        preds.extend(probs.cpu().numpy().flatten())         # ✅ flatten here
        true_labels.extend(labels.cpu().numpy().flatten())  # ✅ flatten here

# Threshold at 0.5
pred_labels = [1 if p > 0.5 else 0 for p in preds]

# Correct: use `true_labels`, not `y_test`
print(classification_report(true_labels, pred_labels))


              precision    recall  f1-score   support

         0.0       0.79      0.70      0.74       197
         1.0       0.74      0.82      0.78       203

    accuracy                           0.76       400
   macro avg       0.76      0.76      0.76       400
weighted avg       0.76      0.76      0.76       400



Switching to MINIlm model since no gpu 


In [ ]:
import transformers
print(transformers.__version__)


In [15]:
pip install --upgrade transformers


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [72]:
pip install transformers datasets scikit-learn


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Defaulting to user installation because normal site-packages is not writeable
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 MB 4.7 MB/s eta 0:00:00m eta 0:00:010:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 1.7 MB/s eta 0:00:001.4 MB/s eta 0:00:01
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.5.1
    Uninstalling fsspec-2025.5.1:
      Successfully uninstalled fsspec-2025.5.1
Note: you may need to restart the kernel to use updated packages.


In [73]:
import pandas as pd

# Example
# df_sample = pd.read_csv("your_dataset.csv")
df_sample["text"] = df_sample["text"].astype(str)
df_sample["target"] = df_sample["target"].astype(int)


In [76]:
from transformers import RobertaTokenizer
from datasets import Dataset

tokenizer = RobertaTokenizer.from_pretrained("distilroberta-base")

# Convert pandas to HuggingFace Dataset
hf_dataset = Dataset.from_pandas(df_sample[['text', 'target']])

# Tokenize
def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

tokenized_dataset = hf_dataset.map(tokenize, batched=True)
tokenized_dataset = tokenized_dataset.rename_column("target", "labels")
tokenized_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

# Train/val split
split = tokenized_dataset.train_test_split(test_size=0.2)


tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

In [78]:
from transformers import RobertaForSequenceClassification

model = RobertaForSequenceClassification.from_pretrained("distilroberta-base", num_labels=2)


model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at distilroberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [87]:
from transformers import TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(pred):
    logits, labels = pred
    preds = logits.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average="binary", zero_division=0)
    acc = accuracy_score(labels, preds)
    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_dir="./logs",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    save_total_limit=2
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=split["train"],
    eval_dataset=split["test"],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)


TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy'

In [85]:
pip uninstall transformers -y

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Found existing installation: transformers 4.52.4
Uninstalling transformers-4.52.4:
  Successfully uninstalled transformers-4.52.4
Note: you may need to restart the kernel to use updated packages.


In [86]:
pip install transformers --upgrade

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Defaulting to user installation because normal site-packages is not writeable
  Using cached transformers-4.52.4-py3-none-any.whl.metadata (38 kB)
Using cached transformers-4.52.4-py3-none-any.whl (10.5 MB)
Note: you may need to restart the kernel to use updated packages.


In [88]:
import transformers
print(transformers.__version__)


4.52.4
